package com.g2inc.scap.editor.gui.wizards.oval.document;
/* ESCAPE Software Copyright 2010 G2, Inc. - All rights reserved.
*
* ESCAPE is open source software distributed under GNU General Public License Version 3.  ESCAPE is not in the public domain 
* and G2, Inc. holds its copyright.  Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:

* 1. Redistributions of ESCAPE source code must retain the above copyright notice, this list of conditions and the following disclaimer. 
* 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the ESCAPE Software distribution. 
* 3. Neither the name of G2, Inc. nor the names of any contributors may be used to endorse or promote products derived from this software without specific prior written permission. 

* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL G2, INC., THE AUTHORS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
* OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
* OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
* OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
* POSSIBILITY OF SUCH DAMAGE.

* You should have received a copy of the GNU General Public License Version 3 along with this program. 
* If not, see http://www.gnu.org/licenses/ for a copy.
*/

import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import org.apache.log4j.Logger;

import com.g2inc.scap.editor.gui.wizards.Wizard;
import com.g2inc.scap.editor.gui.wizards.WizardPage;
import com.g2inc.scap.library.domain.SCAPContentManager;
import com.g2inc.scap.library.domain.SCAPDocumentTypeEnum;

public class CreateOvalPlatformChoicePage extends WizardPage
{
    private static final Logger LOG = Logger.getLogger(CreateOvalPlatformChoicePage.class);
    private SCAPDocumentTypeEnum schemaType;
    private DefaultListModel listModel = null;
    private CreateOvalWizard parentWiz = null;

    private void initComponents2()
    {
        platformList.addListSelectionListener(new ListSelectionListener()
        {
            
            public void valueChanged(ListSelectionEvent e)
            {
                if (e.getValueIsAdjusting() == false)
                {
                    if(e.getFirstIndex() == -1)
                    {
                        setSatisfied(false);
                        parentWiz.disableNextButton();
                        return;
                    }

                    Object[] selectedValueObjects = platformList.getSelectedValues();

                    if(selectedValueObjects == null || selectedValueObjects.length == 0)
                    {
                        setSatisfied(false);
                        parentWiz.disableNextButton();
                        return;
                    }

                    String[] selectedPlatforms = new String[selectedValueObjects.length];
                    for (int i=0; i<selectedValueObjects.length; i++) {
                        selectedPlatforms[i] = (String) selectedValueObjects[i];
                    }


                    setSatisfied(true);
                    parentWiz.enableNextButton();
                    parentWiz.setPlatforms(selectedPlatforms);


                }
            }
        });
    }

    /** Creates new form ChoseVariableTypeWizardPage */
    public CreateOvalPlatformChoicePage()
    {
        initComponents();
        initComponents2();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        notePanel = new javax.swing.JPanel();
        noteLabel = new javax.swing.JLabel();
        platformChoicePanel = new javax.swing.JPanel();
        platformListPane = new javax.swing.JScrollPane();
        platformList = new javax.swing.JList();

        setAutoscrolls(true);
        setMinimumSize(new java.awt.Dimension(250, 300));
        setPreferredSize(new java.awt.Dimension(250, 300));
        setLayout(new java.awt.GridBagLayout());

        notePanel.setAutoscrolls(true);
        notePanel.setLayout(new java.awt.GridBagLayout());

        noteLabel.setText("<HTML>Select one or more platforms to which the definitions in the new OVAL Document will apply</HTML>");
        noteLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        notePanel.add(noteLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        add(notePanel, gridBagConstraints);

        platformChoicePanel.setAutoscrolls(true);
        platformChoicePanel.setLayout(new java.awt.GridBagLayout());

        platformListPane.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());
        platformListPane.setAutoscrolls(true);
        platformListPane.setHorizontalScrollBar(null);

        platformList.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        platformListPane.setViewportView(platformList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        platformChoicePanel.add(platformListPane, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(platformChoicePanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    
    @Override
	public Object getData()
    {
        return platformList.getSelectedValues();
    }

    
    @Override
	public void setData(Object data)
    {
    }

    
    @Override
	public void setWizard(Wizard wizard)
    {
        parentWiz = (CreateOvalWizard) wizard;
        schemaType = parentWiz.getSchemaType();
        SCAPContentManager mgr = null;
        try {
            mgr = SCAPContentManager.getInstance(null);
        } catch (Exception e) {
            LOG.error("Exception initializing SCAPContentManager",e);
        }
        List<String> platforms = mgr.getValidPlatforms(schemaType);
        platformList.removeAll();
        listModel = new DefaultListModel();
        for (int i=0; i<platforms.size(); i++) {
            listModel.addElement(platforms.get(i));
        }
        platformList.setModel(listModel);
    }

    
    @Override
	public String getPageTitle()
    {
        return "Platform type selector";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel noteLabel;
    private javax.swing.JPanel notePanel;
    private javax.swing.JPanel platformChoicePanel;
    private javax.swing.JList platformList;
    private javax.swing.JScrollPane platformListPane;
    // End of variables declaration//GEN-END:variables

    public JList getPlatformList()
    {
        return platformList;
    }

    @Override
	public void performFinish()
    {
    }
}
