//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 09:02:05 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oasis:names:tc:entity:xmlns:xml:catalog", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.g2inc.oasis.xml.catalog;
