//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 09:02:05 AM EDT 
//


package com.g2inc.scap.library.domain.datastream;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.g2inc.scap.library.domain.datastream package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.g2inc.scap.library.domain.datastream
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ComponentRef }
     * 
     */
    public ComponentRef createComponentRef() {
        return new ComponentRef();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link DataStream }
     * 
     */
    public DataStream createDataStream() {
        return new DataStream();
    }

    /**
     * Create an instance of {@link RefListType }
     * 
     */
    public RefListType createRefListType() {
        return new RefListType();
    }

    /**
     * Create an instance of {@link DataStreamCollection }
     * 
     */
    public DataStreamCollection createDataStreamCollection() {
        return new DataStreamCollection();
    }

    /**
     * Create an instance of {@link ExtendedComponent }
     * 
     */
    public ExtendedComponent createExtendedComponent() {
        return new ExtendedComponent();
    }

    /**
     * Create an instance of {@link ContentSourceType }
     * 
     */
    public ContentSourceType createContentSourceType() {
        return new ContentSourceType();
    }

}
