package com.g2inc.scap.editor.gui.windows.xccdf;

/* ESCAPE Software   Copyright 2010 G2, Inc. - All rights reserved.
*
* ESCAPE is open source software distributed under GNU General Public License Version 3.  ESCAPE is not in the public domain 
* and G2, Inc. holds its copyright.  Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:

* 1. Redistributions of ESCAPE source code must retain the above copyright notice, this list of conditions and the following disclaimer. 
* 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the ESCAPE Software distribution. 
* 3. Neither the name of G2, Inc. nor the names of any contributors may be used to endorse or promote products derived from this software without specific prior written permission. 

* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL G2, INC., THE AUTHORS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
* OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
* OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
* OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
* POSSIBILITY OF SUCH DAMAGE.

* You should have received a copy of the GNU General Public License Version 3 along with this program. 
* If not, see http://www.gnu.org/licenses/ for a copy.
*/

import java.util.List;

import javax.swing.JFrame;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import org.apache.log4j.Logger;

import com.g2inc.scap.editor.gui.util.EditorUtil;
import com.g2inc.scap.editor.gui.windows.EditorMainWindow;
import com.g2inc.scap.editor.gui.windows.common.ChangeNotifierPanel;
import com.g2inc.scap.library.domain.xccdf.FrontMatter;
import com.g2inc.scap.library.domain.xccdf.RearMatter;
import com.g2inc.scap.library.domain.xccdf.XCCDFBenchmark;

public class BenchmarkMatterDetailTab extends ChangeNotifierPanel implements ChangeListener
{

    private XCCDFBenchmark benchmark = null;
    private JFrame parentWin = null;
    private static Logger log = Logger.getLogger(BenchmarkMatterDetailTab.class);

    private void initComponents2()
    {
        frontMatterListPanel1.addChangeListener(this);
        rearMatterListPanel1.addChangeListener(this);
    }

    /** Creates new form DefinitionDetailTab */
    public BenchmarkMatterDetailTab()
    {
        initComponents();
        initComponents2();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        frontMatterListPanel1 = new com.g2inc.scap.editor.gui.windows.xccdf.FrontMatterListPanel();
        rearMatterListPanel1 = new com.g2inc.scap.editor.gui.windows.xccdf.RearMatterListPanel();

        setLayout(new java.awt.GridBagLayout());

        frontMatterListPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Front Matter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), java.awt.SystemColor.windowText)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        add(frontMatterListPanel1, gridBagConstraints);

        rearMatterListPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rear Matter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), java.awt.SystemColor.windowText)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        add(rearMatterListPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.g2inc.scap.editor.gui.windows.xccdf.FrontMatterListPanel frontMatterListPanel1;
    private com.g2inc.scap.editor.gui.windows.xccdf.RearMatterListPanel rearMatterListPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public JFrame getParentWin()
    {
        return parentWin;
    }

    @Override
    public void setParentWin(JFrame parentWin)
    {
        this.parentWin = parentWin;
    }

    @Override
    public void stateChanged(ChangeEvent ce)
    {
        Object eventSource = ce.getSource();
        if (eventSource == frontMatterListPanel1)
        {
            benchmark.setFrontMatterList(frontMatterListPanel1.getDoc());
            EditorUtil.markActiveWindowDirty(EditorMainWindow.getInstance(), true);
        }
        else if (eventSource == rearMatterListPanel1)
        {
            benchmark.setRearMatterList(rearMatterListPanel1.getDoc());
            EditorUtil.markActiveWindowDirty(EditorMainWindow.getInstance(), true);
        }
    }

    public void setDoc(XCCDFBenchmark benchmark)
    {
        this.benchmark = benchmark;
        List<FrontMatter> frontMatterList = benchmark.getFrontMatterList();
        frontMatterListPanel1.setDoc(frontMatterList);
        List<RearMatter> rearMatterList = benchmark.getRearMatterList();
        rearMatterListPanel1.setDoc(rearMatterList);
    }
}
