package com.g2inc.scap.editor.gui.wizards.xccdf;
/* ESCAPE Software Copyright 2010 G2, Inc. - All rights reserved.
*
* ESCAPE is open source software distributed under GNU General Public License Version 3.  ESCAPE is not in the public domain 
* and G2, Inc. holds its copyright.  Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:

* 1. Redistributions of ESCAPE source code must retain the above copyright notice, this list of conditions and the following disclaimer. 
* 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the ESCAPE Software distribution. 
* 3. Neither the name of G2, Inc. nor the names of any contributors may be used to endorse or promote products derived from this software without specific prior written permission. 

* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL G2, INC., THE AUTHORS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
* OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
* OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
* OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
* POSSIBILITY OF SUCH DAMAGE.

* You should have received a copy of the GNU General Public License Version 3 along with this program. 
* If not, see http://www.gnu.org/licenses/ for a copy.
*/

import java.util.regex.Pattern;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import org.apache.log4j.Logger;

import com.g2inc.scap.editor.gui.resources.EditorMessages;
import com.g2inc.scap.editor.gui.wizards.Wizard;
import com.g2inc.scap.editor.gui.wizards.WizardPage;

public class CreateXCCDFFilenameChoicePage extends WizardPage implements ChangeListener
{
    private static Logger log = Logger.getLogger(CreateXCCDFFilenameChoicePage.class);
    private CreateXCCDFWizard parentWiz = null;

    //public static String PATTERN_STRING = "^(?!-)(?!(.+[\\\\/]-)).+-xccdf\\.xml$";
    public static String PATTERN_STRING = "^.+$";
    public static String OVERVIEW_STRING = EditorMessages.NEW_XCCDF_WIZARD_FILENAME_CHOICE_NOTE_TEXT;
    public static String FILENAME_CAPTION_STRING = "Filename must end in '-xccdf.xml'";

    private void initFilenamePicker()
    {
        Pattern p = null;
        String pString = PATTERN_STRING;
        try
        {
            p = Pattern.compile(pString);
            filenamePicker.setFilenamePattern(p);
        }
        catch(Exception e)
        {
            log.error("Error compiling pattern " + pString, e);
        }

        filenamePicker.addDefaultExtension("-xccdf.xml");

        filenamePicker.setApproveButtonText("Save");
        filenamePicker.setApproveButtonTooltipText("Save");

        filenamePicker.setBrowseButtonText("Browse");
        filenamePicker.setBrowseButtonTooltipText("Browse for file");

        filenamePicker.setOverviewText(OVERVIEW_STRING);

        filenamePicker.setFilenameCaption(FILENAME_CAPTION_STRING);

        filenamePicker.addChangeListener(this);
    }
    private void initComponents2()
    {
        initFilenamePicker();
    }

    /** Creates new form ChoseVariableTypeWizardPage */
    public CreateXCCDFFilenameChoicePage()
    {
        initComponents();
        initComponents2();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        filenamePicker = new com.g2inc.scap.editor.gui.windows.common.FilenamePicker();

        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(filenamePicker, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public Object getData()
    {
        return getFilename();
    }

    @Override
    public void setData(Object data)
    {       
    }

    @Override
    public void setWizard(Wizard wizard)
    {
        parentWiz = (CreateXCCDFWizard) wizard;
    }

    @Override
    public String getPageTitle()
    {
        return EditorMessages.NEW_XCCDF_WIZARD_FILENAME_CHOICE_PAGE_TITLE;
    }

    public String getFilename()
    {
        return filenamePicker.getFilenameText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.g2inc.scap.editor.gui.windows.common.FilenamePicker filenamePicker;
    // End of variables declaration//GEN-END:variables

    @Override
    public void performFinish()
    {
    }
    
    @Override
    public void stateChanged(ChangeEvent e)
    {
        Object src = e.getSource();

        if(src == filenamePicker)
        {
            if(filenamePicker.isValidFilename())
            {
                setSatisfied(true);
                if(parentWiz != null)
                    parentWiz.enableNextButton();
            }
            else
            {
                setSatisfied(false);
                if(parentWiz != null)
                    parentWiz.disableNextButton();
            }
        }
    }
}
