package com.g2inc.scap.editor.gui.windows.common;
/* ESCAPE Software Copyright 2010 G2, Inc. - All rights reserved.
*
* ESCAPE is open source software distributed under GNU General Public License Version 3.  ESCAPE is not in the public domain 
* and G2, Inc. holds its copyright.  Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:

* 1. Redistributions of ESCAPE source code must retain the above copyright notice, this list of conditions and the following disclaimer. 
* 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the ESCAPE Software distribution. 
* 3. Neither the name of G2, Inc. nor the names of any contributors may be used to endorse or promote products derived from this software without specific prior written permission. 

* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL G2, INC., THE AUTHORS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
* OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
* OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
* OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
* POSSIBILITY OF SUCH DAMAGE.

* You should have received a copy of the GNU General Public License Version 3 along with this program. 
* If not, see http://www.gnu.org/licenses/ for a copy.
*/

import java.awt.Cursor;
import java.io.File;
import java.lang.ref.WeakReference;

import javax.swing.SwingWorker;

import org.apache.log4j.Logger;

import com.g2inc.scap.library.domain.SCAPDocument;
import com.g2inc.scap.library.domain.SCAPDocumentFactory;

/**
 * Dialog to display progress when a document is being loaded.
 *
 * @author ssill2
 */
public class DocumentLoadProgressDialog<T extends SCAPDocument> extends javax.swing.JDialog
{
    private static Logger log = Logger.getLogger(DocumentLoadProgressDialog.class);

    private WeakReference<T> document;
    private File file;
    private boolean done = false;
    private Exception exception = null;
    
    /** Creates new form OperationProgressDialog */
    public DocumentLoadProgressDialog(java.awt.Frame parent, File file)
    {
        super(parent, true);
        initComponents();
        setModal(true);

        this.file = file;

        progressBar.setIndeterminate(true);
        progressBar.setStringPainted(true);
    }

    public T getDocument()
    {
        return document.get();
    }

    public void setMessage(String message)
    {
        messageLabel.setText(message);
    }

    public void setValue(int value)
    {
        progressBar.setValue(value);
    }

    public void setMin(int min)
    {
        progressBar.setMinimum(min);
    }

    public void setMax(int max)
    {
        progressBar.setMaximum(max);
    }

    public boolean getDone()
    {
        return done;
    }

    public Exception getException()
    {
        return exception;
    }

    @Override
    public void setVisible(boolean visible)
    {
        if(visible)
        {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            OpenFileTask task = new OpenFileTask();
            task.execute();
        }
        super.setVisible(visible);
    }

    class OpenFileTask extends SwingWorker<Void, Void>
    {
        /*
         * Main task. Executed in background thread.
         */
        @Override
        public Void doInBackground()
        {
            try
            {
                messageLabel.setText("Loading file " + file.getName());
                document = new WeakReference<T>((T) SCAPDocumentFactory.loadDocument(file));
            }
            catch(Exception e)
            {
                log.error("Exception occurred: " + e.getMessage(), e);
                exception = e;
            }

            done = true;
            return null;
        }

        /*
         * Executed in event dispatching thread
         */
        @Override
        public void done()
        {
            setCursor(null); //turn off the wait cursor
            setVisible(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        messageLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        messageLabel.setText("jLabel1");
        messageLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 8, 0, 8);
        getContentPane().add(messageLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 7, 8);
        getContentPane().add(progressBar, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel messageLabel;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
