package com.g2inc.scap.editor.gui.dialogs.editors.oval.variable;
/* ESCAPE Software Copyright 2010 G2, Inc. - All rights reserved.
*
* ESCAPE is open source software distributed under GNU General Public License Version 3.  ESCAPE is not in the public domain 
* and G2, Inc. holds its copyright.  Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:

* 1. Redistributions of ESCAPE source code must retain the above copyright notice, this list of conditions and the following disclaimer. 
* 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the ESCAPE Software distribution. 
* 3. Neither the name of G2, Inc. nor the names of any contributors may be used to endorse or promote products derived from this software without specific prior written permission. 

* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL G2, INC., THE AUTHORS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
* OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
* OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
* OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
* POSSIBILITY OF SUCH DAMAGE.

* You should have received a copy of the GNU General Public License Version 3 along with this program. 
* If not, see http://www.gnu.org/licenses/ for a copy.
*/

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import com.g2inc.scap.editor.gui.dialogs.editors.EditorDialog;
import com.g2inc.scap.editor.gui.resources.EditorMessages;
import com.g2inc.scap.library.domain.oval.OvalFunction;
import com.g2inc.scap.library.domain.oval.OvalFunctionTimeDifference;

public class FunctionEditorTimeDifference extends FunctionEditor
{
    private void initComponents2()
    {
        initTextFields();
    }

    private void initTextFields()
    {
        format1Text.getDocument().addDocumentListener(new DocumentListener()
        {

            public void insertUpdate(DocumentEvent de)
            {
                common(de);
            }

            public void removeUpdate(DocumentEvent de)
            {
                common(de);
            }

            public void changedUpdate(DocumentEvent de)
            {
                common(de);
            }

            private void common(DocumentEvent de)
            {
                ((OvalFunctionTimeDifference) ovalFunction).setFormat_1(format1Text.getText());
            }
        });
        format2Text.getDocument().addDocumentListener(new DocumentListener()
        {
            public void insertUpdate(DocumentEvent de)
            {
                common(de);
            }

            public void removeUpdate(DocumentEvent de)
            {
                common(de);
            }

            public void changedUpdate(DocumentEvent de)
            {
                common(de);
            }

            private void common(DocumentEvent de)
            {
                ((OvalFunctionTimeDifference) ovalFunction).setFormat_2(format2Text.getText());
            }
        });
    }

    public FunctionEditorTimeDifference()
    {
        initComponents();
        initComponents2();
//        setOvalFunction(function);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        functionEditorPanel1 = new com.g2inc.scap.editor.gui.dialogs.editors.oval.variable.FunctionEditorPanel();
        format1Caption = new javax.swing.JLabel();
        format1Text = new javax.swing.JTextField();
        format2Caption = new javax.swing.JLabel();
        format2Text = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        add(functionEditorPanel1, gridBagConstraints);

        format1Caption.setText("format_1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        add(format1Caption, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 5);
        add(format1Text, gridBagConstraints);

        format2Caption.setText("format_2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        add(format2Caption, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 5);
        add(format2Text, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel format1Caption;
    private javax.swing.JTextField format1Text;
    private javax.swing.JLabel format2Caption;
    private javax.swing.JTextField format2Text;
    private com.g2inc.scap.editor.gui.dialogs.editors.oval.variable.FunctionEditorPanel functionEditorPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setEditorDialog(EditorDialog editorDialog)
    {
        parentEditor = editorDialog;
        parentEditor.setTitle(EditorMessages.OVAL + " 'time_difference' Function Editor");
    }

    @Override
    public void setOvalFunction(OvalFunction function) {
        this.ovalFunction = function;
        functionEditorPanel1.setOvalFunction(function);
        if (function instanceof OvalFunctionTimeDifference) {
            OvalFunctionTimeDifference timeDiffFunction = (OvalFunctionTimeDifference) function;
            if (timeDiffFunction.getFormat_1() != null)
                format1Text.setText((timeDiffFunction.getFormat_1()));
            if (timeDiffFunction.getFormat_2() != null)
                format2Text.setText((timeDiffFunction.getFormat_2()));
        } else {
            throw new IllegalArgumentException("Expected OvalFunctionTimeDifference, got " + ovalFunction.getClass().getName());
        }
    }
}
