package com.g2inc.scap.editor.gui.dialogs.editors.oval.datatype.date;
/* ESCAPE Software Copyright 2010 G2, Inc. - All rights reserved.
*
* ESCAPE is open source software distributed under GNU General Public License Version 3.  ESCAPE is not in the public domain 
* and G2, Inc. holds its copyright.  Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:

* 1. Redistributions of ESCAPE source code must retain the above copyright notice, this list of conditions and the following disclaimer. 
* 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the ESCAPE Software distribution. 
* 3. Neither the name of G2, Inc. nor the names of any contributors may be used to endorse or promote products derived from this software without specific prior written permission. 

* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL G2, INC., THE AUTHORS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
* OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
* OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
* OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
* POSSIBILITY OF SUCH DAMAGE.

* You should have received a copy of the GNU General Public License Version 3 along with this program. 
* If not, see http://www.gnu.org/licenses/ for a copy.
*/

import java.util.Date;

import org.apache.log4j.Logger;

import com.g2inc.scap.editor.gui.dialogs.editors.EditorDialog;
import com.g2inc.scap.editor.gui.dialogs.editors.IEditorPage;

public class WindowsDateDatatypeEditor extends javax.swing.JPanel implements IEditorPage
{
    private static Logger LOG = Logger.getLogger(WindowsDateDatatypeEditor.class);

    private EditorDialog parentEditor = null;

    private void initDatePicker()
    {
        dateEditor.setDateFormatString("MM/dd/yyyy HH:mm:ss a");
    }

    private void initComponents2()
    {
        initDatePicker();
    }

    /** Creates new form RegexDatatypeEditor */
    public WindowsDateDatatypeEditor()
    {
        initComponents();
        initComponents2();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dateCaption = new javax.swing.JLabel();
        dateEditor = new com.toedter.calendar.JSpinnerDateEditor();

        setMinimumSize(new java.awt.Dimension(303, 74));
        setPreferredSize(new java.awt.Dimension(303, 74));
        setLayout(new java.awt.GridBagLayout());

        dateCaption.setText("Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 8, 0, 0);
        add(dateCaption, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 7, 7, 7);
        add(dateEditor, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateCaption;
    private com.toedter.calendar.JSpinnerDateEditor dateEditor;
    // End of variables declaration//GEN-END:variables

    public String getData()
    {
        Date date = dateEditor.getDate();


        return "" + millisToFileTime(date.getTime());
    }

    public void setEditorDialog(EditorDialog editorDialog)
    {
        parentEditor = editorDialog;
        parentEditor.setTitle("Windows Date Editor");
    }

    public void setData(Object data)
    {
        String incoming = (String)data;

        long time = fileTimeToMillies(incoming);

        Date date = new Date(time);

        dateEditor.setDate(date);
    }

    public static long fileTimeToMillies(String fromOval)
    {
        long ret = 0;

        if(fromOval == null || fromOval.length() == 0)
        {
            return ret;
        }
        
        try
        {
            long numericFromOval = Long.parseLong(fromOval);
            ret = (numericFromOval / 10000L) - 11644473600000L;

        }
        catch(NumberFormatException nfe)
        {
           LOG.error("Couldn't convert value " + fromOval + " to a number!", nfe);
        }

        return ret;
    }

    public static  long millisToFileTime(long fromJava)
    {
        long ret = 0;

        ret = (fromJava + 11644473600000L) * 10000L;

        return ret;
    }

}
