package com.g2inc.scap.editor.gui.dialogs.editors.oval.variable;
/* ESCAPE Software Copyright 2010 G2, Inc. - All rights reserved.
*
* ESCAPE is open source software distributed under GNU General Public License Version 3.  ESCAPE is not in the public domain 
* and G2, Inc. holds its copyright.  Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:

* 1. Redistributions of ESCAPE source code must retain the above copyright notice, this list of conditions and the following disclaimer. 
* 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the ESCAPE Software distribution. 
* 3. Neither the name of G2, Inc. nor the names of any contributors may be used to endorse or promote products derived from this software without specific prior written permission. 

* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL G2, INC., THE AUTHORS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
* OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
* OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
* OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
* POSSIBILITY OF SUCH DAMAGE.

* You should have received a copy of the GNU General Public License Version 3 along with this program. 
* If not, see http://www.gnu.org/licenses/ for a copy.
*/

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import com.g2inc.scap.editor.gui.choosers.variable.VariableChooser;
import com.g2inc.scap.editor.gui.dialogs.editors.EditorDialog;
import com.g2inc.scap.editor.gui.dialogs.editors.IEditorPage;
import com.g2inc.scap.library.domain.oval.OvalDefinitionsDocument;
import com.g2inc.scap.library.domain.oval.OvalVariable;
import com.g2inc.scap.library.domain.oval.OvalVariableComponentVariable;

public class VariableComponentEditor extends javax.swing.JPanel implements IEditorPage
{
    private OvalVariableComponentVariable varComp = null;
    private EditorDialog parentEditor = null;
    private OvalDefinitionsDocument ovalDoc;
    private OvalVariable ovalVariable = null;

    private void initButtons()
    {
        chooseVariableButton.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent ae)
            {
                VariableChooser chooser = new VariableChooser(true);
                chooser.setSource(varComp.getParentDocument(), null, null);
                chooser.setVisible(true);

                if(!chooser.wasCancelled())
                {
                    ovalVariable = (OvalVariable) chooser.getChosen();
                    variableLabel.setText(ovalVariable.getId());
                    varComp.setVariableId(ovalVariable.getId());
                    parentEditor.enableOkButton();
                }
            }
        });
    }

    private void initComponents2()
    {
        initButtons();
    }

    public VariableComponentEditor()
    {
        initComponents();
//        setOvalVariableComponentVariable(varComp);
        initComponents2();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        variableCaption = new javax.swing.JLabel();
        variableLabel = new javax.swing.JLabel();
        chooseVariableButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        variableCaption.setText("Variable");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(9, 10, 0, 2);
        add(variableCaption, gridBagConstraints);

        variableLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        variableLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        variableLabel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        variableLabel.setMinimumSize(new java.awt.Dimension(128, 255));
        variableLabel.setPreferredSize(new java.awt.Dimension(128, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 4, 4);
        add(variableLabel, gridBagConstraints);

        chooseVariableButton.setText("Choose Variable");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 5, 5);
        add(chooseVariableButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseVariableButton;
    private javax.swing.JLabel variableCaption;
    private javax.swing.JLabel variableLabel;
    // End of variables declaration//GEN-END:variables

    public String getData()
    {   
        return null;
    }

    public void setEditorDialog(EditorDialog editorDialog)
    {
        parentEditor = editorDialog;
        parentEditor.setTitle("Variable Component Editor");
    }

    public void setData(Object data)
    {
    	setOvalVariableComponentVariable((OvalVariableComponentVariable) data);
    }

    private void setOvalVariableComponentVariable(OvalVariableComponentVariable varComp) {
        this.varComp = varComp;
        ovalVariable = varComp.getVariable();
        if (ovalVariable != null)
        {
            variableLabel.setText(ovalVariable.getId());
        }
    }
}
